image: 
  file: .gitpod.Dockerfile

tasks:
  - name: 1a-yb
    before: |
      mkdir -p ${GITPOD_REPO_ROOT}/ybdb
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd1 --listen=127.0.0.1 --tserver_flags="placement_cloud=ybcloud,placement_region=ap-south-1,placement_zone=ap-south-1a" --master_flags="placement_cloud=ybcloud,placement_region=ap-south-1,placement_zone=ap-south-1a"
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd2 --listen=127.0.0.2 --join=127.0.0.1 --tserver_flags="placement_cloud=ybcloud,placement_region=ap-south-1,placement_zone=ap-south-1b" --master_flags="placement_cloud=ybcloud,placement_region=ap-south-1,placement_zone=ap-south-1b"
      yugabyted start --base_dir=${GITPOD_REPO_ROOT}/ybdb/ybd3 --listen=127.0.0.3 --join=127.0.0.1 --tserver_flags="placement_cloud=ybcloud,placement_region=ap-south-1,placement_zone=ap-south-1c" --master_flags="placement_cloud=ybcloud,placement_region=ap-south-1,placement_zone=ap-south-1c"
      yb-admin -master_addresses 127.0.0.1:7100,127.0.0.2:7100,127.0.0.3:7100 modify_placement_info ybcloud.ap-south-1.ap-south-1a,ybcloud.ap-south-1.ap-south-1b,ybcloud.ap-south-1.ap-south-1c 3
    command: |
      gp await-port 5433
      ysqlsh
  - name: postgres
    init: |
      brew install libpq && brew link --force libpq
      docker pull postgres
    command: |
      docker run --name postgresql -e POSTGRES_USER=postgres -e POSTGRES_HOST_AUTH_METHOD=trust -p 5432:5432 -v ~/postgresql_data/:/var/lib/postgresql/data -d postgres
      gp ports await 5432
      sleep 10
      psql postgresql://postgres:postgres@localhost
